### ISSUE TITLE
Update travis tests to use multiple versions of nuodb

### ISSUE THREAD

**Issue by jgetto** [nuodb/perl-dbd-nuodb#2]
Right now the travis tests only test 1.0GA nuodb. They should test all supported versions, so probably 1.0, 1.0.1, 1.0.2, 1.1

See the python driver travis file for a starting point.

**Comment by madscientist** [comment]
In an ideal world all versions would be tested, but that's a lot of overhead.  Even tracking all supported versions is an ongoing maintenance battle as new versions are released and old versions are dropped from support.

Currently I've updated the travis file so it automatically tests with the latest released version.  If I can convince the Nuo folks who manage the download site to maintain a list of supported versions then we can switch to that.
